### ISSUE TITLE
Displaying multiple instances of the "cubx-component-docs-viewer" on the same page fails.

### ISSUE THREAD

**Issue by hrbu** [cubbles/cubx-webpackage-viewer#4]
On https://cubbles.world/sandbox/flinkster-car-search@0.1.0-SNAPSHOT/docs/index.html I tried to use multiple instances of the `cubx-component-docs-viewer`. It failed with an error on javascript level (something with `svg.parentNode()...`).

Please check it out and provide a fix if possible.

**Comment by edwingamboa** [comment]
The fix was included in the [cubx-webpackage-viewer@1.7.1 release](https://github.com/cubbles/cubx-webpackage-viewer/releases/tag/1.7.1)

A working demo is available [here](https://cubbles.world/sandbox/com.incowia.cubx-webpackage-viewer@1.7.1-SNAPSHOT/cubx-component-docs-viewer/demo/index.html).

**Comment by edwingamboa** [comment]
Tabs in the `cubx-component-docs-viewer` behave incorrectly when there are more than one instance of the component in the same webpage since those have the same 'id'. The collapse panels of the dep-tree-viewer have a similar behaviour

**Comment by edwingamboa** [comment]
Fixes were done in `cubx-generic-component-viewer`, `cubx-component-docs-viewer` and `cubx-dep-tree-viewer`
