### ISSUE TITLE
The cubx-webpackage-viewer does not display the data of compounds' members correctly

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubx-webpackage-viewer#7]

**Comment by edwingamboa** [comment]
The bug was solved for modelVersion 10 (2.0.0-SNAPSHOT version available in develop branch) and modelVersion 1.9.1 (1.7.2 Version)

Demos: [1.7.2](https://cubbles.world/sandbox/com.incowia.cubx-webpackage-viewer@1.7.2/cubx-webpackage-viewer/demo/index.html), [2.0.0-SNAPSHOT](https://cubbles.world/sandbox/com.incowia.cubx-webpackage-viewer@2.0.0-SNAPSHOT/cubx-webpackage-viewer/demo/index.html).

The 1.7.2 version was released in [GitHub](https://github.com/cubbles/cubx-webpackage-viewer/releases/tag/1.7.2) too

**Comment by pwrinc** [comment]
Thanks @edwingamboa for creating the issue. The problem I mentioned regarding the bug in the list of members seems to be fixed now.
